"""
market_map_data.py — AUTO-GENERATED on 2026-06-09 09:34
Source file date: 8_6_26
DO NOT EDIT MANUALLY — regenerate by running auto_populate_market_map.py
"""
import pandas as pd


def get_state_data(state_name: str) -> pd.DataFrame:
    """Return district-level brand volume DataFrame for the given state."""
    data_store = {
        "Andhra Pradesh": {
            "District": ['ANANTAPUR', 'GUNTUR', 'VISAKHAPATNAM'],
            "Colour_Frame": [0.0, 0.0, 0.0],
            "AM/NS": [0.0, 0.0, 0.0],
            "APL Apollo": [0.0, 0.0, 0.0],
            "PROMPT": [0.0, 0.0, 0.0],
            "HI TECH": [0.0, 0.0, 0.0],
            "RCS": [0.0, 0.0, 0.0],
            "Others": [32.2, 228.9, 38.7],
        },
        "Assam": {
            "District": ['KAMRUP METROPOLITAN'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [13.1],
        },
        "Bihar": {
            "District": ['MUZAFFARPUR', 'PATNA'],
            "Colour_Frame": [0.0, 0.0],
            "AM/NS": [0.0, 0.0],
            "APL Apollo": [0.0, 0.0],
            "PROMPT": [0.0, 0.0],
            "HI TECH": [0.0, 0.0],
            "RCS": [0.0, 0.0],
            "Others": [78.1, 29.4],
        },
        "Chhattisgarh": {
            "District": ['RAIPUR'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [71.7],
        },
        "Delhi": {
            "District": ['NEW DELHI', 'SOUTH'],
            "Colour_Frame": [0.0, 0.0],
            "AM/NS": [0.0, 0.0],
            "APL Apollo": [0.0, 0.0],
            "PROMPT": [0.0, 0.0],
            "HI TECH": [0.0, 0.0],
            "RCS": [0.0, 0.0],
            "Others": [8.7, 39.6],
        },
        "Goa": {
            "District": ['NORTH GOA'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [94.4],
        },
        "Gujarat": {
            "District": ['KHEDA', 'MAHESANA'],
            "Colour_Frame": [0.0, 0.0],
            "AM/NS": [0.0, 0.0],
            "APL Apollo": [0.0, 0.0],
            "PROMPT": [0.0, 0.0],
            "HI TECH": [0.0, 0.0],
            "RCS": [0.0, 0.0],
            "Others": [38.9, 118.7],
        },
        "Haryana": {
            "District": ['FARIDABAD', 'HISAR', 'PALWAL', 'SIRSA'],
            "Colour_Frame": [27.1, 0.0, 0.0, 83.4],
            "AM/NS": [0.0, 0.0, 0.0, 0.0],
            "APL Apollo": [0.0, 0.0, 0.0, 0.0],
            "PROMPT": [0.0, 0.0, 0.0, 0.0],
            "HI TECH": [0.0, 0.0, 0.0, 0.0],
            "RCS": [0.0, 0.0, 0.0, 0.0],
            "Others": [0.0, 32.8, 40.4, 0.0],
        },
        "Karnataka": {
            "District": ['BANGALORE URBAN', 'BELLARY', 'DAKSHINA KANNADA'],
            "Colour_Frame": [0.0, 0.0, 0.0],
            "AM/NS": [0.0, 0.0, 0.0],
            "APL Apollo": [0.0, 0.0, 0.0],
            "PROMPT": [0.0, 0.0, 0.0],
            "HI TECH": [0.0, 0.0, 0.0],
            "RCS": [0.0, 0.0, 0.0],
            "Others": [98.5, 31.6, 199.0],
        },
        "Kerala": {
            "District": ['ERNAKULAM', 'KOLLAM', 'KOZHIKODE', 'PALAKKAD', 'PATHANAMTHITTA', 'THRISSUR'],
            "Colour_Frame": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "AM/NS": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "APL Apollo": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "PROMPT": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "HI TECH": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "RCS": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "Others": [34.2, 33.3, 33.7, 23.6, 63.5, 29.3],
        },
        "Madhya Pradesh": {
            "District": ['INDORE'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [56.1],
        },
        "Maharashtra": {
            "District": ['AHMEDNAGAR', 'AURANGABAD', 'JALGAON', 'LATUR', 'PUNE', 'RAIGARH', 'SANGLI', 'SATARA', 'THANE'],
            "Colour_Frame": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "AM/NS": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "APL Apollo": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "PROMPT": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "HI TECH": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "RCS": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "Others": [64.6, 39.2, 73.0, 32.8, 51.1, 199.7, 54.0, 39.0, 64.3],
        },
        "Punjab": {
            "District": ['LUDHIANA'],
            "Colour_Frame": [9.9],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [14.8],
        },
        "Rajasthan": {
            "District": ['JAIPUR'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [146.9],
        },
        "Tamil Nadu": {
            "District": ['TIRUVALLUR'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [88.2],
        },
        "Telangana": {
            "District": ['HYDERABAD'],
            "Colour_Frame": [0.0],
            "AM/NS": [0.0],
            "APL Apollo": [0.0],
            "PROMPT": [0.0],
            "HI TECH": [0.0],
            "RCS": [0.0],
            "Others": [58.3],
        },
        "Uttar Pradesh": {
            "District": ['GHAZIABAD', 'VARANASI'],
            "Colour_Frame": [163.6, 0.0],
            "AM/NS": [0.0, 0.0],
            "APL Apollo": [0.0, 0.0],
            "PROMPT": [0.0, 0.0],
            "HI TECH": [0.0, 0.0],
            "RCS": [0.0, 0.0],
            "Others": [67.8, 37.6],
        },
        "West Bengal": {
            "District": ['HOWRAH', 'KOLKATA'],
            "Colour_Frame": [0.0, 0.0],
            "AM/NS": [0.0, 0.0],
            "APL Apollo": [0.0, 0.0],
            "PROMPT": [0.0, 0.0],
            "HI TECH": [0.0, 0.0],
            "RCS": [0.0, 0.0],
            "Others": [56.9, 13.1],
        },
    }

    if state_name not in data_store:
        raise ValueError(f"No dispatch data found for state: {state_name}")

    return pd.DataFrame(data_store[state_name])


AVAILABLE_STATES = [
    "Andhra Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Punjab",
    "Rajasthan",
    "Tamil Nadu",
    "Telangana",
    "Uttar Pradesh",
    "West Bengal",
]